import "./globals.css";

import { AuthContextProvider } from "@/context/AuthContext";
import PrelineScript from "@/components/PrelineScript";
import NavBar from "../components/NavBar";
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <AuthContextProvider>
        <NavBar />
        {children}
        <PrelineScript />
        <NextTopLoader />
      </AuthContextProvider>
      </body>
    </html>
  );
}
