const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.webp',
      price: 80,
      brand: 'Tommy hilfiger',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Popular Shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpeg',
      price: 80,
      brand: 'American Eagle',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Classic Shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpeg',
      price: 80,
      brand: 'Louis Vuttton',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Fantastic Shirt',
    },
    {
      name: 'Slim-Fit Pants',
      slug: 'slim-pants',
      category: 'Pants',
      image: '/images/Pant1.jpeg',
      price: 80,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Popular Pant',
    },
    {
      name: 'Classic-Fit Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/Pant2.jpeg',
      price: 80,
      brand: 'Armani',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Gorgeous lokking Pant',
    },
  ],
}

export default data
